### ISSUE TITLE
"0 games were renamed" with 0.139 XML, DAT files and mame64.exe

### ISSUE THREAD

**Issue by jedcooper** [gerrykeys/playnite-mame-utility#14]
As title. I have tried the XML file, the DAT file and the mame64.exe executable.
I have imported the games via automatic scan into Playnite, their names are their ROM names, so mk for mk.zip ROM i.e. Mortal Kombat etc.

**Comment by gerrykeys** [comment]
Hello,
0.139 is an older version of mame that i think is not compatible with my plugin. 
I am in vacation now and i cannot do a check but i am pretty sure that the xml format for this version contains a data structure that is different respect the new versions of name.

I don’t remember if my plugin specify the version number compatibility of mame, but i should put this information if it is missing.

**Comment by jedcooper** [comment]
BTW is there a limit for renaming? I select the whole Arcade import (~30k titles) and it's only renaming parts of it in one run. Same goes with cleaner. I have to reselect manually very often, many times few chunks of 100 titles.

**Comment by JFERDZ** [comment]
Hello!
I’m sorry for reopening this, but I’m having this same problem here.
“0 games were renamed”
And I’m using:
PlayNite 10.34
MAME Utility 1.0.6
MAME 0.270
ROMset (merged) 0.260

**Comment by gerrykeys** [comment]
Hi @JFERDZ 
let me test, i will let know you.
Thanks

**Comment by gerrykeys** [comment]
> Hello! I’m sorry for reopening this, but I’m having this same problem here. “0 games were renamed” And I’m using: PlayNite 10.34 MAME Utility 1.0.6 MAME 0.270 ROMset (merged) 0.260

Hi @JFERDZ 

I noticed that you are using a different version of MAME (0.270) from the romset (0.260).
Consider that if you are using MAME exe (or xml file) as data source in the settings of my extensions, some of games could not be renamed because romset version must match the version of the data source.

I did a test with the romset 0.270 and used the gamelist.xml source data 0.270 and it works fine.

Beside that, are you sure that you have selected games in the Palynite list?
The plugin will rename only your current game selection.

I just released a new version of the plugin (1.0.7) in which i did an improvements for that:
now, if you have no selection from the game list i will show a popup message that alert you.

**Comment by JFERDZ** [comment]
It's working!

Tested on:
PlayNite 10.34
MAME Utility 1.0.7
MAME 0.271
ROMset (merged) 0.271

So, the versions must have some overlap for it to work?

**Comment by gerrykeys** [comment]
Hey @JFERDZ 

the version issue is not a problema form my plugin, but generally the romset version should match with the source data generated by MAME.exe (or from xml file) because the name of the roms could change from a different versions.
